NAME_ROW_NO = 1
DEFINITION_ROW_NO = 2
MAIN_FUNCTION_ROW_NO = 3
ADDITIONAL_FUNCTION_ROW_NO = 4
FORM_ROW_NO = 5
PART_ROW_NO = 6
WHOLE_ROW_NO = 7
COMMENT_ROW_NO = 9
SYNONYM_PL_ROW_NO = 11
SYNONYM_EN_ROW_NO = 12
SYNONYM_LAT_ROW_NO = 13
SYNONYM_DE_ROW_NO = 14
SYNONYM_FR_ROW_NO = 15
SYNONYM_RUS_ROW_NO = 16
SIMILAR_TERMS_NO = 17
OTHER_DEF_ROW_NO = 18
BDOT_L1_ROW_NO = 20
BDOT_L2_ROW_NO = 21
BDOT_L3_ROW_NO = 22
WIKIDATA_ROW_NO = 24
AUTHOR_ROW_NO = 25

OBJECT_TYPE_LOCAL_FRAGMENT = 'object_type'

EXCEL_SHEET_SHAPE = (27, 3)
